#!/bin/bash

## Takes the name of the robot as a single argument (ex. "./generate_dar_from_urdf.sh darci")

#Generate URDF from Xacro files
rosrun xacro xacro.py ./urdf/$1.urdf.xacro > ./urdf/$1.urdf

#Convert URDF to SDF
gzsdf print ./urdf/$1.urdf > sdf/model.sdf

#Fix Links as generated by the gzsdf command
sed -i "s/gt_meka_description\/urdf/$1/g" sdf/model.sdf
